Repository TemateuRoslyn/uv_projet_in3_2023, pull requests merged in 2023-06, with the labels that each got.

#60 Closes #46 - My Account Settings added
  src/frontend/web/react-admin/src/App.tsx
  src/frontend/web/react-admin/src/components/DropdownUser.tsx
Labels: enhancement

#67 Close #59 creation du model et definition des differentes routes pour…
  src/backend/laravel-app/app/Http/Controllers/API/NotificationController.php
  src/backend/laravel-app/database/migrations/2023_05_29_000000_create_notifications_table.php
  src/backend/laravel-app/routes/api.php
Labels: enhancement

#73 Closes #65 - Add admin, user, permission and roles menus
  src/frontend/web/react-admin/src/App.tsx
  src/frontend/web/react-admin/src/components/Sidebar.tsx
  src/frontend/web/react-admin/src/components/SidebarLinkGroup.tsx
  src/frontend/web/react-admin/src/pages/Admin/AdminPermission.tsx
  src/frontend/web/react-admin/src/pages/Admin/AdminPermissionForm.tsx
  src/frontend/web/react-admin/src/pages/Admin/AdminRole.tsx
  src/frontend/web/react-admin/src/pages/Admin/AdminRoleForm.tsx
  src/frontend/web/react-admin/src/pages/Admin/AdminUser.tsx
  src/frontend/web/react-admin/src/pages/Admin/AdminUserForm.tsx
  src/frontend/web/react-admin/src/pages/AdminUser.tsx
Labels: enhancement

#74 Closes #57 - Creation des middlewares manquants
  src/backend/laravel-app/.rnd
  src/backend/laravel-app/app/Http/Kernel.php
  src/backend/laravel-app/app/Http/Middleware/EleveMiddleware.php
  src/backend/laravel-app/app/Http/Middleware/ParentMiddleware.php
  src/backend/laravel-app/app/Http/Middleware/PersonnelMiddleware.php
  src/backend/laravel-app/app/Http/Middleware/ProfesseurMiddleware.php
  src/backend/laravel-app/app/Models/Faute.php
  src/backend/laravel-app/app/Models/Reparation.php
  src/backend/laravel-app/composer.lock
  src/backend/laravel-app/database/migrations/2023_05_31_203005_create_fautes_table.php
  src/backend/laravel-app/database/migrations/2023_05_31_204941_create_reparations_table.php
  src/backend/laravel-app/database/seeders/PermissionSeeder.php
  src/backend/laravel-app/database/seeders/RoleSeeder.php
Labels: enhancement

#75 Closes #61 - Creation des roles et permissions manquantes
  src/backend/laravel-app/app/Http/Kernel.php
Labels: enhancement

#83 Closes #82 - creation du splash scrren et des onboarding pages de app…
  src/frontend/mobile/flutter_app/assets/images/logo.png
  src/frontend/mobile/flutter_app/assets/images/onBoardingOne.png
  src/frontend/mobile/flutter_app/assets/images/onBoardingThree.png
  src/frontend/mobile/flutter_app/assets/images/onBoardingTwo.png
  src/frontend/mobile/flutter_app/lib/common/styles/colors.dart
  src/frontend/mobile/flutter_app/lib/common/utils/constants.dart
  src/frontend/mobile/flutter_app/lib/common/utils/helper.dart
  src/frontend/mobile/flutter_app/lib/common/views/onBoarding_one.dart
  src/frontend/mobile/flutter_app/lib/common/views/onBoarding_three.dart
  src/frontend/mobile/flutter_app/lib/common/views/onBoarding_two.dart
  src/frontend/mobile/flutter_app/lib/common/views/splash_page.dart
  src/frontend/mobile/flutter_app/lib/common/widgets/fields.dart
  src/frontend/mobile/flutter_app/lib/features/authentication/views/register_page.dart
  src/frontend/mobile/flutter_app/lib/main.dart
  src/frontend/mobile/flutter_app/lib/repositories/auth_repository.dart
  src/frontend/mobile/flutter_app/pubspec.lock
  src/frontend/mobile/flutter_app/pubspec.yaml
Labels: enhancement

#104 Closes #103 - Dark mode bug fixed
  src/frontend/web/react-admin/src/index.css
  src/frontend/web/react-site/src/App.css
Labels: enhancement

#119 Closes #108 Personnel: Controlleur, Routes, Migrations,Seeders
  src/backend/laravel-app/app/Http/Controllers/API/PersonnelController.php
  src/backend/laravel-app/routes/api.php
Labels: enhancement

#130 Closes #112 - modification de la carte
  src/frontend/web/react-admin/src/App.tsx
  src/frontend/web/react-site/src/components/contact/Contact.jsx
Labels: enhancement

#140 Closes #120 - CRUD pages for Faults
  run.react.web.sh
  src/backend/laravel-app/app/Http/Controllers/API/EleveController.php
  src/backend/laravel-app/composer.lock
  src/frontend/web/react-admin/src/App.tsx
  src/frontend/web/react-admin/src/components/Sidebar.tsx
  src/frontend/web/react-admin/src/generated/package.json
  src/frontend/web/react-admin/src/index.css
  src/frontend/web/react-admin/src/main.tsx
  src/frontend/web/react-admin/src/pages/Admin/Faults/AddFaults.tsx
  src/frontend/web/react-admin/src/pages/Admin/Faults/FaultsGrid.tsx
  src/frontend/web/react-admin/src/pages/Admin/Faults/ListFaults.tsx
  src/frontend/web/react-admin/src/pages/Admin/ReglementInterieur/AddReglement.tsx
  src/frontend/web/react-admin/src/pages/Admin/ReglementInterieur/ReglementGrid.tsx
  src/frontend/web/react-admin/src/pages/AppSwitch.tsx
  src/frontend/web/react-admin/src/pages/Authentication/SignIn/SignIn.tsx
Labels: enhancement

#142 Closes #110 #111 Creation du controleur et Seeder, definition des rou…
  src/backend/laravel-app/app/Http/Controllers/API/EleveController.php
  src/backend/laravel-app/app/Http/Controllers/API/PersonnelController.php
  src/backend/laravel-app/app/Http/Controllers/API/RegleController.php
  src/backend/laravel-app/app/Http/Controllers/API/ReglementInterieurController.php
  src/backend/laravel-app/app/Models/Regle.php
  src/backend/laravel-app/app/Models/ReglementInterieur.php
  src/backend/laravel-app/composer.lock
  src/backend/laravel-app/database/seeders/DatabaseSeeder.php
  src/backend/laravel-app/database/seeders/RegleSeeder.php
  src/backend/laravel-app/database/seeders/ReglementInterieurSeeder.php
  src/backend/laravel-app/routes/api.php
  src/backend/laravel-app/storage/api-docs/api-docs.json
Labels: Feature

#143 Closes #107 Creation du controleur et seeder, definition des routes e…
  src/backend/laravel-app/app/Http/Controllers/API/CourController.php
  src/backend/laravel-app/app/Models/Cour.php
  src/backend/laravel-app/app/Models/Professeur.php
  src/backend/laravel-app/database/migrations/2023_05_30_000006_create_professeurs_table.php
  src/backend/laravel-app/database/migrations/2023_05_31_000005_create_cours_table.php
  src/backend/laravel-app/database/seeders/CoursSeeder.php
  src/backend/laravel-app/database/seeders/UserSeeder.php
  src/backend/laravel-app/routes/api.php
Labels: Feature

#150 Closes #109 ROUTES,Contoller ,Migrations, Seeder de l'entite Professeur
  src/backend/laravel-app/app/Http/Controllers/API/ProfesseurController.php
  src/backend/laravel-app/app/Models/Cour.php
  src/backend/laravel-app/app/Models/Professeur.php
  src/backend/laravel-app/database/migrations/2023_05_30_000005_create_cours_table.php
  src/backend/laravel-app/database/migrations/2023_05_30_000006_create_professeurs_table.php
  src/backend/laravel-app/database/seeders/DatabaseSeeder.php
  src/backend/laravel-app/database/seeders/ProfesseurSeeder.php
  src/backend/laravel-app/routes/api.php
Labels: Feature

#152 Closes #151 - Navigation to signup page done
  run.react.admin.sh
  run.web.react.sh
  src/frontend/web/react-admin/src/components/DropdownUser.tsx
Labels: Fixe, Feature

#168 Closes #167 - Correction des endPoint
  src/frontend/web/react-admin/src/pages/Admin/Permission/components/DisplayPermissions.tsx
  src/frontend/web/react-admin/src/pages/Admin/Role/components/DisplayRoles.tsx
  src/frontend/web/react-admin/src/pages/Admin/cours/Cours.page.tsx
  src/frontend/web/react-admin/src/pages/Admin/cours/components/DisplayCours.tsx
  src/frontend/web/react-admin/src/pages/Classe/components/DisplayClasses.tsx
Labels: Feature

#173 Closes #172 - API Integrated
  src/backend/laravel-app/app/Http/Controllers/API/RegleController.php
  src/frontend/web/react-admin/src/components/Sidebar.tsx
  src/frontend/web/react-admin/src/generated/apis/regles-api.ts
  src/frontend/web/react-admin/src/generated/models/regle-create-body.ts
  src/frontend/web/react-admin/src/pages/AppSwitch/AppSwitch.tsx
  src/frontend/web/react-admin/src/pages/Regle/Regle.page.tsx
  src/frontend/web/react-admin/src/pages/Regle/components/CreateOrUpdateRegleModal.tsx
  src/frontend/web/react-admin/src/pages/Regle/components/DisplayRegle.css
  src/frontend/web/react-admin/src/pages/Regle/components/DisplayRegle.tsx
  src/frontend/web/react-site/src/generated/apis/regles-api.ts
  src/frontend/web/react-site/src/generated/models/regle-create-body.ts
Labels: Feature

#176 Closes #175 - Theme responsiveness fixe
  src/frontend/web/react-admin/src/pages/Admin/Permission/components/CreateOrUpdatePermissionModal.tsx
  src/frontend/web/react-admin/src/pages/Admin/Role/components/CreateOrUpdateRoleModal.tsx
  src/frontend/web/react-admin/src/pages/Admin/cours/components/CreateOrUpdateCoursModal.tsx
  src/frontend/web/react-admin/src/pages/Classe/components/CreateOrUpdateClasseModal.tsx
  src/frontend/web/react-admin/src/pages/Eleve/components/CreateOrUpdateEleveModal.tsx
  src/frontend/web/react-admin/src/pages/Regle/components/CreateOrUpdateRegleModal.tsx
  src/frontend/web/react-admin/src/pages/ReglementInterieur/components/CreateOrUpdateReglementInterieurModal.tsx
Labels: Feature

#178 Task 177
  src/backend/laravel-app/app/Http/Controllers/API/EleveController.php
  src/frontend/web/react-admin/src/components/AgGridCells/ImageCelleRender.tsx
  src/frontend/web/react-admin/src/components/DropdownUser.tsx
  src/frontend/web/react-admin/src/configs/ag-grid-column-def/eleve.ts
  src/frontend/web/react-admin/src/pages/Admin/Permission/components/CreateOrUpdatePermissionModal.tsx
  src/frontend/web/react-admin/src/pages/Admin/Role/components/CreateOrUpdateRoleModal.tsx
  src/frontend/web/react-admin/src/pages/AppSwitch/AppSwitch.tsx
  src/frontend/web/react-admin/src/pages/Authentication/SignIn/SignIn.tsx
  src/frontend/web/react-admin/src/pages/Classe/components/CreateOrUpdateClasseModal.tsx
  src/frontend/web/react-admin/src/pages/Eleve/components/CreateOrUpdateEleveModal.tsx
  src/frontend/web/react-admin/src/pages/Regle/components/CreateOrUpdateRegleModal.tsx
  src/frontend/web/react-admin/src/pages/ReglementInterieur/components/CreateOrUpdateReglementInterieurModal.tsx
  src/frontend/web/react-admin/src/pages/cours/Cours.page.tsx
  src/frontend/web/react-admin/src/pages/cours/components/CreateOrUpdateCoursModal.tsx
  src/frontend/web/react-admin/src/pages/cours/components/DisplayCours.css
  src/frontend/web/react-admin/src/pages/cours/components/DisplayCours.tsx
Labels: Feature

#184 Closes #180 - navigation de app et page de profil ajoutes
  src/frontend/mobile/flutter_app/assets/images/login.png
  src/frontend/mobile/flutter_app/assets/images/unknown_contact_img.png
  src/frontend/mobile/flutter_app/lib/common/configurations/api_configuration.dart
  src/frontend/mobile/flutter_app/lib/common/logics/navigation/cubit/navigation_cubit.dart
  src/frontend/mobile/flutter_app/lib/common/logics/navigation/cubit/navigation_cubit.freezed.dart
  src/frontend/mobile/flutter_app/lib/common/logics/navigation/cubit/navigation_state.dart
  src/frontend/mobile/flutter_app/lib/common/styles/colors.dart
  src/frontend/mobile/flutter_app/lib/common/utils/constants.dart
  src/frontend/mobile/flutter_app/lib/common/utils/enums.dart
  src/frontend/mobile/flutter_app/lib/common/views/loading_page.dart
  src/frontend/mobile/flutter_app/lib/common/views/onBoarding_one.dart
  src/frontend/mobile/flutter_app/lib/common/views/onBoarding_three.dart
  src/frontend/mobile/flutter_app/lib/common/views/onBoarding_two.dart
  src/frontend/mobile/flutter_app/lib/common/views/page_skeleton.dart
  src/frontend/mobile/flutter_app/lib/common/views/splash_page.dart
  src/frontend/mobile/flutter_app/lib/common/widgets/common_widgets.dart
  src/frontend/mobile/flutter_app/lib/common/widgets/fields.dart
  src/frontend/mobile/flutter_app/lib/common/widgets/modals_and_animated_dialogs.dart
  src/frontend/mobile/flutter_app/lib/features/authentication/logic/authentication/bloc/authentication_bloc.dart
  src/frontend/mobile/flutter_app/lib/features/authentication/logic/login/login_cubit.dart
  src/frontend/mobile/flutter_app/lib/features/authentication/logic/login/login_cubit.freezed.dart
  src/frontend/mobile/flutter_app/lib/features/authentication/logic/login/login_state.dart
  src/frontend/mobile/flutter_app/lib/features/authentication/views/login_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/home_page.dart
  src/frontend/mobile/flutter_app/lib/features/profile/views/profile_page.dart
  src/frontend/mobile/flutter_app/lib/main.dart
  src/frontend/mobile/flutter_app/lib/repositories/auth_repository.dart
  src/frontend/mobile/flutter_app/linux/flutter/generated_plugin_registrant.cc
  src/frontend/mobile/flutter_app/linux/flutter/generated_plugins.cmake
  src/frontend/mobile/flutter_app/macos/Flutter/GeneratedPluginRegistrant.swift
  src/frontend/mobile/flutter_app/pubspec.lock
  src/frontend/mobile/flutter_app/pubspec.yaml
  src/frontend/mobile/flutter_app/windows/flutter/generated_plugin_registrant.cc
  src/frontend/mobile/flutter_app/windows/flutter/generated_plugins.cmake
Labels: Feature

#189 Closes #179 - terminer avec la consommation de la route authentificat…
  src/frontend/mobile/flutter_app/lib/common/configurations/api_configuration.dart
  src/frontend/mobile/flutter_app/lib/common/logics/internet/internet_cubit.dart
  src/frontend/mobile/flutter_app/lib/common/logics/internet/internet_state.dart
  src/frontend/mobile/flutter_app/lib/common/logics/navigation/navigation_cubit.dart
  src/frontend/mobile/flutter_app/lib/common/logics/navigation/navigation_cubit.freezed.dart
  src/frontend/mobile/flutter_app/lib/common/logics/navigation/navigation_state.dart
  src/frontend/mobile/flutter_app/lib/common/models/user.dart
  src/frontend/mobile/flutter_app/lib/common/views/check_internet_page.dart
  src/frontend/mobile/flutter_app/lib/common/views/loading_page.dart
  src/frontend/mobile/flutter_app/lib/common/views/onBoarding_three.dart
  src/frontend/mobile/flutter_app/lib/common/views/page_skeleton.dart
  src/frontend/mobile/flutter_app/lib/common/widgets/fields.dart
  src/frontend/mobile/flutter_app/lib/features/authentication/logic/login/login_cubit.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/home_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/widgets/home_component.dart
  src/frontend/mobile/flutter_app/lib/features/profile/logic/profile_cubit.dart
  src/frontend/mobile/flutter_app/lib/features/profile/logic/profile_cubit.freezed.dart
  src/frontend/mobile/flutter_app/lib/features/profile/logic/profile_state.dart
  src/frontend/mobile/flutter_app/lib/main.dart
  src/frontend/mobile/flutter_app/lib/repositories/auth_repository.dart
  src/frontend/mobile/flutter_app/macos/Flutter/GeneratedPluginRegistrant.swift
  src/frontend/mobile/flutter_app/pubspec.lock
  src/frontend/mobile/flutter_app/pubspec.yaml
  src/frontend/web/react-admin/src/generated/apis/auth-api.ts~HEAD
  src/frontend/web/react-admin/src/generated/apis/auth-api.ts~a1cb1f4... Closes #179 - consommation du login et de la route findOne de eleve
  src/frontend/web/react-admin/src/generated/apis/parents-api.ts~HEAD
  src/frontend/web/react-admin/src/generated/apis/parents-api.ts~a1cb1f4... Closes #179 - consommation du login et de la route findOne de eleve
  src/frontend/web/react-admin/src/generated/models/auth-login-body.ts~HEAD
  src/frontend/web/react-admin/src/generated/models/auth-login-body.ts~a1cb1f4... Closes #179 - consommation du login et de la route findOne de eleve
  src/frontend/web/react-admin/src/generated/models/eleves-update-body.ts~HEAD
  src/frontend/web/react-admin/src/generated/models/eleves-update-body.ts~a1cb1f4... Closes #179 - consommation du login et de la route findOne de eleve
  src/frontend/web/react-admin/src/generated/models/inline-response404.ts~HEAD
  src/frontend/web/react-admin/src/generated/models/inline-response404.ts~a1cb1f4... Closes #179 - consommation du login et de la route findOne de eleve
  src/frontend/web/react-admin/src/generated/models/user.ts~HEAD
  src/frontend/web/react-admin/src/generated/models/user.ts~a1cb1f4... Closes #179 - consommation du login et de la route findOne de eleve
  src/frontend/web/react-site/src/generated/apis/auth-api.ts~HEAD
  src/frontend/web/react-site/src/generated/apis/auth-api.ts~a1cb1f4... Closes #179 - consommation du login et de la route findOne de eleve
  src/frontend/web/react-site/src/generated/apis/parents-api.ts~HEAD
  src/frontend/web/react-site/src/generated/apis/parents-api.ts~a1cb1f4... Closes #179 - consommation du login et de la route findOne de eleve
  src/frontend/web/react-site/src/generated/models/auth-login-body.ts~HEAD
  src/frontend/web/react-site/src/generated/models/auth-login-body.ts~a1cb1f4... Closes #179 - consommation du login et de la route findOne de eleve
  src/frontend/web/react-site/src/generated/models/eleves-update-body.ts~HEAD
  src/frontend/web/react-site/src/generated/models/eleves-update-body.ts~a1cb1f4... Closes #179 - consommation du login et de la route findOne de eleve
  src/frontend/web/react-site/src/generated/models/inline-response404.ts~HEAD
  src/frontend/web/react-site/src/generated/models/inline-response404.ts~a1cb1f4... Closes #179 - consommation du login et de la route findOne de eleve
  src/frontend/web/react-site/src/generated/models/reglement-create-body.ts~HEAD
  src/frontend/web/react-site/src/generated/models/reglement-create-body.ts~a1cb1f4... Closes #179 - consommation du login et de la route findOne de eleve
  src/frontend/web/react-site/src/generated/models/reglement-update-body.ts~HEAD
  src/frontend/web/react-site/src/generated/models/reglement-update-body.ts~a1cb1f4... Closes #179 - consommation du login et de la route findOne de eleve
  src/frontend/web/react-site/src/generated/models/user.ts~HEAD
  src/frontend/web/react-site/src/generated/models/user.ts~a1cb1f4... Closes #179 - consommation du login et de la route findOne de eleve
Labels: Feature

#190 closes #153 - crud professeur
  src/frontend/web/react-admin/src/components/Sidebar.tsx
  src/frontend/web/react-admin/src/configs/ag-grid-column-def/professeur.ts
  src/frontend/web/react-admin/src/pages/AppSwitch/AppSwitch.tsx
  src/frontend/web/react-admin/src/pages/Enseignant/Professeurs.page.tsx
  src/frontend/web/react-admin/src/pages/Enseignant/components/CreateOrUpdateProfesseurModal.tsx
  src/frontend/web/react-admin/src/pages/Enseignant/components/DisplayProfesseurs.css
  src/frontend/web/react-admin/src/pages/Enseignant/components/DisplayProfesseurs.tsx
Labels: Feature

#193 Closes #191 entite Faute
  src/backend/laravel-app/app/Http/Controllers/API/FauteController.php
  src/backend/laravel-app/app/Http/Controllers/API/ProfesseurController.php
  src/backend/laravel-app/app/Models/Faute.php
  src/backend/laravel-app/database/seeders/DatabaseSeeder.php
  src/backend/laravel-app/database/seeders/FauteSeeder.php
  src/backend/laravel-app/routes/api.php
Labels: Feature

#195 Closes #194 Crud de l'entite ConseilDiscipline
  src/backend/laravel-app/app/Http/Controllers/API/ConseilDisciplineController.php
  src/backend/laravel-app/app/Models/ConseilDiscipline.php
  src/backend/laravel-app/composer.lock
  src/backend/laravel-app/database/migrations/2023_05_30_000014_create_conseil_disciplines_table.php
  src/backend/laravel-app/database/seeders/ConseilDisciplineSeeder.php
  src/backend/laravel-app/database/seeders/DatabaseSeeder.php
  src/backend/laravel-app/routes/api.php
Labels: Feature

#199 Closes #198 - Auth Api added successfully
  src/frontend/web/react-admin/src/components/DropdownUser.tsx
  src/frontend/web/react-admin/src/configs/ag-grid-column-def/professeur.ts
  src/frontend/web/react-admin/src/generated/package.json
  src/frontend/web/react-admin/src/pages/Eleve/components/CreateOrUpdateEleveModal.tsx
  src/frontend/web/react-site/package-lock.json
  src/frontend/web/react-site/package.json
  src/frontend/web/react-site/src/App.css
  src/frontend/web/react-site/src/App.jsx
  src/frontend/web/react-site/src/components/common/back/Back.jsx
  src/frontend/web/react-site/src/components/login/components/Indicator.tsx
  src/frontend/web/react-site/src/components/login/login.css
  src/frontend/web/react-site/src/components/login/login.tsx
  src/frontend/web/react-site/src/constants/ENUM.ts
  src/frontend/web/react-site/src/constants/ITEMS.ts
  src/frontend/web/react-site/src/constants/LOCAL_STORAGE.ts
  src/frontend/web/react-site/src/constants/RESPONSES_CODE.ts
  src/frontend/web/react-site/src/constants/STATE.ts
  src/frontend/web/react-site/src/environments/environment.dev.ts
  src/frontend/web/react-site/src/environments/environment.prod.ts
  src/frontend/web/react-site/src/environments/environment.ts
  src/frontend/web/react-site/src/generated/package.json
  src/frontend/web/react-site/src/main.jsx
  src/frontend/web/react-site/src/redux/Actions/EnvironmentAction.ts
  src/frontend/web/react-site/src/redux/Actions/LoggedInAction.ts
  src/frontend/web/react-site/src/redux/Actions/TokenAction.ts
  src/frontend/web/react-site/src/redux/Actions/UserAction.ts
  src/frontend/web/react-site/src/redux/Constants/ConstantsRedux.ts
  src/frontend/web/react-site/src/redux/Reducers/EnvironmentReducer.ts
  src/frontend/web/react-site/src/redux/Reducers/IsLOggedReducer.ts
  src/frontend/web/react-site/src/redux/Reducers/TokenReducer.ts
  src/frontend/web/react-site/src/redux/Reducers/UserReducer.ts
  src/frontend/web/react-site/src/redux/configureStore.ts
  src/frontend/web/react-site/vite.config.ts.timestamp-1687873238728-02374f102cff5.mjs
Labels: Feature

#205 Closes #202 - Mobile view of suggestion box
  src/frontend/mobile/flutter_app/lib/common/widgets/fields.dart
  src/frontend/mobile/flutter_app/lib/features/authentication/views/login_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/suggestion_box.dart
  src/frontend/mobile/flutter_app/lib/features/profile/views/profile_page.dart
  src/frontend/mobile/flutter_app/lib/main.dart
  src/frontend/mobile/flutter_app/pubspec.lock
Labels: Feature

#213 Closes #203 Relationship eleve_parent
  src/backend/laravel-app/app/Http/Controllers/API/EleveParentController.php
  src/backend/laravel-app/app/Http/Controllers/API/ParentsController.php
  src/backend/laravel-app/app/Models/Eleve.php
  src/backend/laravel-app/app/Models/Parents.php
  src/backend/laravel-app/database/migrations/2023_05_30_000003_create_parents_table.php
  src/backend/laravel-app/database/migrations/2023_06_26_232836_create_eleve_parent_table.php
  src/backend/laravel-app/database/seeders/DatabaseSeeder.php
  src/backend/laravel-app/database/seeders/ParentSeeder.php
  src/backend/laravel-app/routes/api.php
Labels: Feature

#219 Closes #214 - application des modifs au niveau du login et consommati…
  src/frontend/mobile/flutter_app/lib/common/configurations/api_configuration.dart
  src/frontend/mobile/flutter_app/lib/common/models/reglements_interieurs.dart
  src/frontend/mobile/flutter_app/lib/common/utils/constants.dart
  src/frontend/mobile/flutter_app/lib/common/views/check_internet_page.dart
  src/frontend/mobile/flutter_app/lib/common/views/page_skeleton_two.dart
  src/frontend/mobile/flutter_app/lib/common/widgets/common_widgets.dart
  src/frontend/mobile/flutter_app/lib/features/authentication/logic/login/login_cubit.dart
  src/frontend/mobile/flutter_app/lib/features/authentication/views/login_page.dart
  src/frontend/mobile/flutter_app/lib/features/authentication/views/register_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/logic/home_cubit.dart
  src/frontend/mobile/flutter_app/lib/features/home/logic/home_cubit.freezed.dart
  src/frontend/mobile/flutter_app/lib/features/home/logic/home_state.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/fautes_sanctions_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/home_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/reglements_interieurs_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/widgets/RI_components.dart
  src/frontend/mobile/flutter_app/lib/features/home/widgets/fautes_et_sanctions_component.dart
  src/frontend/mobile/flutter_app/lib/features/profile/views/profile_page.dart
  src/frontend/mobile/flutter_app/lib/main.dart
  src/frontend/mobile/flutter_app/lib/repositories/auth_repository.dart
  src/frontend/mobile/flutter_app/lib/repositories/home_repository.dart
Labels: Feature

#212 Page programme du website
  src/frontend/web/react-admin/src/generated/models/inline-response20016.ts
  src/frontend/web/react-site/src/components/allcourses/CourseHome.jsx
  src/frontend/web/react-site/src/components/allcourses/CoursesCard.jsx
  src/frontend/web/react-site/src/components/allcourses/OnlineCourses.jsx
  src/frontend/web/react-site/src/components/allcourses/courses.css
  src/frontend/web/react-site/src/components/common/header/Header.jsx
  src/frontend/web/react-site/src/components/common/heading/Heading.jsx
  src/frontend/web/react-site/src/dummydata.js
Labels: Feature

#224 Closes #223 CRUD Reparation
  src/backend/laravel-app/app/Http/Controllers/API/ReparationController.php
  src/backend/laravel-app/app/Models/Reparation.php
  src/backend/laravel-app/database/migrations/2023_06_28_154319_create_reparations_table.php
  src/backend/laravel-app/database/seeders/DatabaseSeeder.php
  src/backend/laravel-app/database/seeders/ReparationSeeder.php
  src/backend/laravel-app/routes/api.php
Labels: Feature

#226 Closes #215 - convocation,fautes,professeurs
  src/backend/laravel-app/app/Http/Controllers/API/ProfesseurController.php
  src/backend/laravel-app/routes/api.php
Labels: Feature

#227 Closes #225 correction Doc de parent
  src/backend/laravel-app/app/Models/Parents.php
Labels: bug

#234 Closes #222 - Creation des api crud de la table sanction prevu
  src/backend/laravel-app/app/Http/Controllers/API/SanctionPrevuController.php
  src/backend/laravel-app/app/Models/SanctionPrevu.php
  src/backend/laravel-app/database/migrations/2023_05_31_000016_create_sanction_prevus_table.php
  src/backend/laravel-app/routes/api.php
Labels: In progress

#236 Closes #235 - ajout des middlewares sur les routes fautes, convocation et professeurs
  src/backend/laravel-app/routes/api.php
Labels: In progress

#240 Closes #239 - gestion des roles dans app et quelques modifications fa…
  src/frontend/mobile/flutter_app/lib/common/views/check_internet_page.dart
  src/frontend/mobile/flutter_app/lib/common/views/page_skeleton.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/courses.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/home_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/reglements_interieurs_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/suggestion_box.dart
  src/frontend/mobile/flutter_app/lib/features/home/widgets/course_component.dart
  src/frontend/mobile/flutter_app/lib/features/profile/views/profile_page.dart
  src/frontend/mobile/flutter_app/lib/main.dart
  src/frontend/mobile/flutter_app/lib/repositories/auth_repository.dart
  src/frontend/mobile/flutter_app/lib/repositories/home_repository.dart
Labels: Feature

#242 Closes #241 Notification:Controlleur,Models,Routes
  src/backend/laravel-app/app/Http/Controllers/API/NotificationController.php
  src/backend/laravel-app/app/Models/Notification.php
  src/backend/laravel-app/routes/api.php
Labels: Feature

#245 Closes #238 - Convocation component
  src/frontend/mobile/flutter_app/lib/common/styles/colors.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/convocation.dart
  src/frontend/mobile/flutter_app/lib/features/home/widgets/convocation_component.dart
  src/frontend/mobile/flutter_app/lib/main.dart
  src/frontend/mobile/flutter_app/pubspec.lock
  src/frontend/mobile/flutter_app/pubspec.yaml
Labels: In progress

#249 Closes #247 - Correction de l'entite Regle
  src/backend/laravel-app/app/Http/Controllers/API/RegleController.php
  src/backend/laravel-app/app/Http/Controllers/API/ReglementInterieurController.php
  src/backend/laravel-app/app/Models/Regle.php
  src/backend/laravel-app/app/Models/ReglementInterieur.php
  src/backend/laravel-app/database/migrations/2023_05_30_000009_create_reglement_interieurs_table.php
  src/backend/laravel-app/database/migrations/2023_05_30_000010_create_regles_table.php
  src/backend/laravel-app/database/migrations/2023_05_30_000011_create_fautes_table.php
  src/backend/laravel-app/database/migrations/2023_06_28_154319_create_reparations_table.php
  src/backend/laravel-app/database/seeders/RegleSeeder.php
  src/backend/laravel-app/routes/api.php
Labels: bug

#251 Closes #250 - Fixing bugs of the documentation
  src/backend/laravel-app/app/Http/Controllers/API/ConseilDisciplineController.php
  src/backend/laravel-app/app/Http/Controllers/API/CourController.php
  src/backend/laravel-app/app/Http/Controllers/API/FauteController.php
  src/backend/laravel-app/app/Http/Controllers/API/ProfesseurController.php
  src/backend/laravel-app/app/Http/Controllers/API/RegleController.php
  src/backend/laravel-app/app/Http/Controllers/API/ReglementInterieurController.php
  src/backend/laravel-app/app/Http/Controllers/API/SanctionPrevuController.php
  src/backend/laravel-app/routes/api.php
Labels: bug
