Repository TemateuRoslyn/uv_projet_in3_2023, pull requests merged in 2023-07, with the labels that each got.

#256 Closes #255 - Adding relationship on Regle, Faute and ConseilDiscipli…
  src/backend/laravel-app/app/Http/Controllers/API/ConseilDisciplineController.php
  src/backend/laravel-app/app/Http/Controllers/API/FauteController.php
  src/backend/laravel-app/app/Http/Controllers/API/RegleController.php
  src/backend/laravel-app/app/Models/ConseilDiscipline.php
  src/backend/laravel-app/app/Models/Regle.php
Labels: Feature

#258 Closes #257 - creation des api crud de la table AvoirMembreConseilDiscipline
  src/backend/laravel-app/app/Http/Controllers/API/AvoirMembreConseilDisciplineController.php
  src/backend/laravel-app/app/Http/Controllers/API/ClassesController.php
  src/backend/laravel-app/app/Http/Controllers/API/ProfesseurController.php
  src/backend/laravel-app/app/Models/AvoirMembreConseilDiscipline.php
  src/backend/laravel-app/app/Models/Classe.php
  src/backend/laravel-app/app/Models/Professeur.php
  src/backend/laravel-app/database/migrations/2023_05_30_000006_create_professeurs_table.php
  src/backend/laravel-app/database/migrations/2023_05_30_000007_create_classes_table.php
  src/backend/laravel-app/database/migrations/2023_06_28_224602_create_avoir_membre_conseil_disciplines_table.php
  src/backend/laravel-app/database/seeders/ParentSeeder.php
  src/backend/laravel-app/database/seeders/ProfesseurSeeder.php
  src/backend/laravel-app/routes/api.php
Labels: In progress

#262 Closes #261 - correction des api crud associe a la table cour
  src/backend/laravel-app/app/Http/Controllers/API/CourController.php
  src/backend/laravel-app/app/Models/Cour.php
  src/backend/laravel-app/app/Models/CoursClasse.php
  src/backend/laravel-app/database/migrations/2023_06_26_142504_create_cours_classes_table.php
  src/backend/laravel-app/database/seeders/CoursClasseSeeder.php
  src/backend/laravel-app/database/seeders/CoursSeeder.php
  src/backend/laravel-app/database/seeders/DatabaseSeeder.php
  src/backend/laravel-app/routes/api.php
Labels: In progress

#265 Closes #263 - correction des api crud de la table classe
  src/backend/laravel-app/app/Http/Controllers/API/ClassesController.php
  src/backend/laravel-app/app/Http/Controllers/API/ProfesseurController.php
  src/backend/laravel-app/app/Models/Classe.php
  src/backend/laravel-app/app/Models/ClasseProfesseur.php
  src/backend/laravel-app/app/Models/Professeur.php
  src/backend/laravel-app/database/migrations/2023_05_30_000006_create_professeurs_table.php
  src/backend/laravel-app/database/migrations/2023_07_01_113945_create_classe_professeurs_table.php
  src/backend/laravel-app/database/seeders/ClasseProfesseurSeeder.php
  src/backend/laravel-app/database/seeders/DatabaseSeeder.php
  src/backend/laravel-app/database/seeders/ProfesseurSeeder.php
Labels: In progress

#266 Closes #264 - gestion du role parents terminee et quelques modificati…
  src/frontend/mobile/flutter_app/lib/common/configurations/api_configuration.dart
  src/frontend/mobile/flutter_app/lib/common/models/faute.dart
  src/frontend/mobile/flutter_app/lib/common/models/reglement_interieur.dart
  src/frontend/mobile/flutter_app/lib/common/models/user.dart
  src/frontend/mobile/flutter_app/lib/common/views/page_skeleton.dart
  src/frontend/mobile/flutter_app/lib/common/widgets/common_widgets.dart
  src/frontend/mobile/flutter_app/lib/features/home/logic/home_cubit.dart
  src/frontend/mobile/flutter_app/lib/features/home/logic/home_cubit.freezed.dart
  src/frontend/mobile/flutter_app/lib/features/home/logic/home_state.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/convocation_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/courses_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/fautes_sanctions_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/home_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/reglements_interieurs_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/suggestion_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/widgets/convocation_component.dart
  src/frontend/mobile/flutter_app/lib/features/home/widgets/course_component.dart
  src/frontend/mobile/flutter_app/lib/features/profile/views/profile_page.dart
  src/frontend/mobile/flutter_app/lib/main.dart
  src/frontend/mobile/flutter_app/lib/repositories/auth_repository.dart
  src/frontend/mobile/flutter_app/lib/repositories/home_repository.dart
  src/frontend/mobile/flutter_app/macos/Runner.xcodeproj/project.pbxproj
  src/frontend/mobile/flutter_app/pubspec.lock
Labels: Feature

#268 Closes #267 - correction des api crud de la table faute
  src/backend/laravel-app/app/Http/Controllers/API/ConseilDisciplineController.php
  src/backend/laravel-app/app/Http/Controllers/API/FauteController.php
  src/backend/laravel-app/app/Models/ConseilDiscipline.php
  src/backend/laravel-app/app/Models/Eleve.php
  src/backend/laravel-app/app/Models/Faute.php
  src/backend/laravel-app/app/Models/Regle.php
  src/backend/laravel-app/routes/api.php
Labels: In progress

#271 Closes #270 - correction des api crud de convocation
  src/backend/laravel-app/app/Http/Controllers/API/ConvocationController.php
  src/backend/laravel-app/app/Models/Convocation.php
  src/backend/laravel-app/database/migrations/2023_05_30_000013_create_convocations_table.php
  src/backend/laravel-app/database/seeders/ConvocationSeeder.php
  src/backend/laravel-app/routes/api.php
Labels: Feature

#273 Closes #272 - creation des api crud de la table suggestion
  src/backend/laravel-app/app/Http/Controllers/API/ClassesController.php
  src/backend/laravel-app/app/Http/Controllers/API/ProfesseurController.php
  src/backend/laravel-app/app/Http/Controllers/API/SuggestionsController.php
  src/backend/laravel-app/app/Models/Classe.php
  src/backend/laravel-app/app/Models/Cour.php
  src/backend/laravel-app/app/Models/Suggestion.php
  src/backend/laravel-app/database/migrations/2023_07_02_141536_create_suggestions_table.php
  src/backend/laravel-app/database/seeders/ClasseProfesseurSeeder.php
  src/backend/laravel-app/database/seeders/CoursClasseSeeder.php
  src/backend/laravel-app/database/seeders/DatabaseSeeder.php
  src/backend/laravel-app/database/seeders/ProfesseurSeeder.php
  src/backend/laravel-app/database/seeders/SuggestionSeeder.php
  src/backend/laravel-app/routes/api.php
Labels: Feature

#275 Closes #274 - consommation des routes convocations, conseils de disci…
  .vscode/launch.json
  src/frontend/mobile/flutter_app/lib/common/configurations/api_configuration.dart
  src/frontend/mobile/flutter_app/lib/common/models/conseil_discipline.dart
  src/frontend/mobile/flutter_app/lib/common/models/convocation.dart
  src/frontend/mobile/flutter_app/lib/common/models/faute.dart
  src/frontend/mobile/flutter_app/lib/common/models/regle.dart
  src/frontend/mobile/flutter_app/lib/common/views/page_skeleton.dart
  src/frontend/mobile/flutter_app/lib/features/authentication/logic/login/login_cubit.dart
  src/frontend/mobile/flutter_app/lib/features/home/logic/home_cubit.dart
  src/frontend/mobile/flutter_app/lib/features/home/logic/home_cubit.freezed.dart
  src/frontend/mobile/flutter_app/lib/features/home/logic/home_state.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/conseil_discipline_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/convocation_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/fautes_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/home_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/reglements_interieurs_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/widgets/convocation_component.dart
  src/frontend/mobile/flutter_app/lib/features/home/widgets/course_component.dart
  src/frontend/mobile/flutter_app/lib/features/profile/views/parent_consultation_page.dart
  src/frontend/mobile/flutter_app/lib/features/profile/views/profile_page.dart
  src/frontend/mobile/flutter_app/lib/repositories/auth_repository.dart
  src/frontend/mobile/flutter_app/lib/repositories/home_repository.dart
Labels: Feature

#277 Closes #276 - creation des api de la table convocation et adaptation …
  src/backend/laravel-app/app/Http/Controllers/API/ConseilDisciplineController.php
  src/backend/laravel-app/app/Http/Controllers/API/EleveController.php
  src/backend/laravel-app/app/Http/Controllers/API/FauteController.php
  src/backend/laravel-app/app/Http/Controllers/API/ParentsController.php
  src/backend/laravel-app/app/Http/Controllers/API/SuggestionsController.php
  src/backend/laravel-app/app/Models/ConseilDiscipline.php
  src/backend/laravel-app/app/Models/Parents.php
  src/backend/laravel-app/app/Models/ReglementInterieur.php
  src/backend/laravel-app/database/migrations/2023_05_30_000014_create_conseil_disciplines_table.php
  src/backend/laravel-app/database/seeders/ConseilDisciplineSeeder.php
  src/backend/laravel-app/routes/api.php
Labels: Feature

#279 Closes #278 - Login redirection corrected
  src/frontend/web/react-admin/src/components/DeleteItemModal.tsx
  src/frontend/web/react-admin/src/pages/Eleve/components/DisplayEleves.tsx
  src/frontend/web/react-admin/src/pages/Regle/Regle.page.tsx
  src/frontend/web/react-admin/src/pages/Regle/components/DisplayRegle.tsx
  src/frontend/web/react-admin/src/pages/ReglementInterieur/ReglementInterieur.page.tsx
  src/frontend/web/react-admin/src/pages/ReglementInterieur/components/DisplayReglementInterieur.tsx
  src/frontend/web/react-site/src/components/common/header/Header.jsx
  src/frontend/web/react-site/src/components/login/login.tsx
Labels: Feature

#292 #Closes 291 Modification des verbes http de la route pour la methode …
  src/backend/laravel-app/.env.example
  src/backend/laravel-app/app/Http/Controllers/API/ConseilDisciplineController.php
  src/backend/laravel-app/app/Http/Controllers/API/CourController.php
  src/backend/laravel-app/app/Http/Controllers/API/EleveController.php
  src/backend/laravel-app/app/Http/Controllers/API/FauteController.php
  src/backend/laravel-app/app/Http/Controllers/API/ParentsController.php
  src/backend/laravel-app/app/Http/Controllers/API/ProfesseurController.php
  src/backend/laravel-app/app/Http/Controllers/API/RegleController.php
  src/backend/laravel-app/app/Http/Controllers/API/ReglementInterieurController.php
  src/backend/laravel-app/app/Http/Controllers/API/ReparationController.php
  src/backend/laravel-app/app/Http/Controllers/API/SanctionPrevuController.php
  src/backend/laravel-app/app/Http/Controllers/API/SuggestionsController.php
  src/backend/laravel-app/app/Http/Controllers/API/UserController.php
  src/backend/laravel-app/composer.lock
  src/backend/laravel-app/routes/api.php
Labels: Fixe

#294 Closes #293 - initialisation effective des notification, de audio et …
  src/frontend/mobile/flutter_app/android/app/build.gradle
  src/frontend/mobile/flutter_app/android/app/src/main/res/drawable/logo.png
  src/frontend/mobile/flutter_app/android/build.gradle
  src/frontend/mobile/flutter_app/assets/images/logo_test.jpg
  src/frontend/mobile/flutter_app/lib/common/models/user.dart
  src/frontend/mobile/flutter_app/lib/common/services/notification.dart
  src/frontend/mobile/flutter_app/lib/common/services/socket_io.dart
  src/frontend/mobile/flutter_app/lib/common/services/text_to_speech.dart
  src/frontend/mobile/flutter_app/lib/common/widgets/common_widgets.dart
  src/frontend/mobile/flutter_app/lib/features/authentication/views/login_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/logic/home_cubit.dart
  src/frontend/mobile/flutter_app/lib/features/home/logic/home_cubit.freezed.dart
  src/frontend/mobile/flutter_app/lib/features/home/logic/home_state.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/conseil_discipline_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/convocation_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/fautes_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/home_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/reglements_interieurs_page.dart
  src/frontend/mobile/flutter_app/lib/features/profile/views/parent_consultation_page.dart
  src/frontend/mobile/flutter_app/lib/features/profile/views/profile_page.dart
  src/frontend/mobile/flutter_app/lib/repositories/home_repository.dart
  src/frontend/mobile/flutter_app/macos/Flutter/GeneratedPluginRegistrant.swift
  src/frontend/mobile/flutter_app/pubspec.lock
  src/frontend/mobile/flutter_app/pubspec.yaml
  src/frontend/mobile/flutter_app/windows/flutter/generated_plugin_registrant.cc
  src/frontend/mobile/flutter_app/windows/flutter/generated_plugins.cmake
Labels: Feature

#296 Closes #290 - Correction l'API Eleve
  src/backend/laravel-app/app/Http/Controllers/API/EleveController.php
  src/backend/laravel-app/database/migrations/2023_05_30_000011_create_fautes_table.php
  src/backend/laravel-app/database/migrations/2023_05_30_000013_create_convocations_table.php
  src/backend/laravel-app/database/migrations/2023_05_30_000014_create_conseil_disciplines_table.php
Labels: Feature

#298 Closes #297 - corrections des api de fautes et sanction prevu
  src/backend/laravel-app/app/Http/Controllers/API/EleveController.php
  src/backend/laravel-app/app/Http/Controllers/API/FauteController.php
  src/backend/laravel-app/app/Http/Controllers/API/MembreConseilController.php
  src/backend/laravel-app/app/Http/Controllers/API/SanctionPrevuController.php
  src/backend/laravel-app/app/Models/SanctionPrevu.php
  src/backend/laravel-app/composer.lock
  src/backend/laravel-app/database/migrations/2023_05_31_000016_create_sanction_prevus_table.php
  src/backend/laravel-app/database/seeders/MembreConseil.php
  src/backend/laravel-app/routes/api.php
Labels: Feature

#313 Closes #312 - EndPoints pour lecture des suggestions
  src/backend/laravel-app/app/Http/Controllers/API/SuggestionsController.php
  src/backend/laravel-app/app/Models/Suggestion.php
  src/backend/laravel-app/database/migrations/2023_07_02_141536_create_suggestions_table.php
  src/backend/laravel-app/database/seeders/SuggestionSeeder.php
  src/backend/laravel-app/routes/api.php
Labels: Feature

#321 Closes #320 - Correction de ConseilDiscipline
  src/backend/laravel-app/app/Http/Controllers/API/ConseilDisciplineController.php
  src/backend/laravel-app/app/Models/ConseilDiscipline.php
  src/backend/laravel-app/database/migrations/2023_05_30_000014_create_conseil_disciplines_table.php
  src/backend/laravel-app/database/seeders/ConseilDisciplineSeeder.php
  src/backend/laravel-app/routes/api.php
  src/frontend/web/react-admin/src/configs/ag-grid-column-def/conseilDiscipline.ts
  src/frontend/web/react-admin/src/generated/apis/conseil-disciplines-api.ts
  src/frontend/web/react-admin/src/generated/models/conseil-discipline.ts
  src/frontend/web/react-site/src/generated/apis/conseil-disciplines-api.ts
  src/frontend/web/react-site/src/generated/models/conseil-discipline.ts
Labels: Feature

#332 Closes #331 - ajout de l'api pour la conversion de l'ensemble des fau…
  src/backend/laravel-app/app/Http/Controllers/API/FauteController.php
  src/backend/laravel-app/routes/api.php
Labels: Feature

#334 Task 333
  src/backend/laravel-app/app/Http/Controllers/API/CourController.php
  src/backend/laravel-app/routes/api.php
  src/frontend/web/react-admin/src/components/AgGridCells/ListCellRenderer.tsx
  src/frontend/web/react-admin/src/components/Header.tsx
  src/frontend/web/react-admin/src/generated/package.json
  src/frontend/web/react-admin/src/pages/AppSwitch/AppSwitch.tsx
  src/frontend/web/react-admin/src/pages/AppSwitch/NotFound.tsx
  src/frontend/web/react-admin/src/pages/cours/components/CreateOrUpdateCoursModal.tsx
  src/frontend/web/react-admin/src/pages/cours/components/DisplayCours.tsx
  src/frontend/web/react-site/src/api/apis/reglement-interieurs-api.ts
  src/frontend/web/react-site/src/api/apis/suggestions-api.ts
  src/frontend/web/react-site/src/api/models/inline-response20081.ts
  src/frontend/web/react-site/src/api/models/inline-response20082.ts
  src/frontend/web/react-site/src/api/models/inline-response20087.ts
  src/frontend/web/react-site/src/api/models/inline-response20089.ts
  src/frontend/web/react-site/src/api/models/inline-response20090.ts
  src/frontend/web/react-site/src/api/models/inline-response20091.ts
  src/frontend/web/react-site/src/api/models/inline-response20092.ts
  src/frontend/web/react-site/src/api/models/inline-response40037-error.ts
  src/frontend/web/react-site/src/components/AppSwitch/AppSwitch.tsx
  src/frontend/web/react-site/src/components/AppSwitch/NotFound.tsx
  src/frontend/web/react-site/src/generated/api.ts
  src/frontend/web/react-site/src/generated/apis/conseil-disciplines-api.ts
  src/frontend/web/react-site/src/generated/apis/eleves-api.ts
  src/frontend/web/react-site/src/generated/apis/fautes-api.ts
  src/frontend/web/react-site/src/generated/apis/reglement-interieurs-api.ts
  src/frontend/web/react-site/src/generated/apis/regles-api.ts
  src/frontend/web/react-site/src/generated/apis/reparations-api.ts
  src/frontend/web/react-site/src/generated/apis/roles-api.ts
  src/frontend/web/react-site/src/generated/apis/sanctionprevus-api.ts
  src/frontend/web/react-site/src/generated/apis/suggestions-api.ts
  src/frontend/web/react-site/src/generated/apis/users-api.ts
  src/frontend/web/react-site/src/generated/models/conseil-discipline.ts
  src/frontend/web/react-site/src/generated/models/index.ts
  src/frontend/web/react-site/src/generated/models/inline-response20071.ts
  src/frontend/web/react-site/src/generated/models/inline-response20072.ts
  src/frontend/web/react-site/src/generated/models/inline-response20073.ts
  src/frontend/web/react-site/src/generated/models/inline-response20074.ts
  src/frontend/web/react-site/src/generated/models/inline-response20075.ts
  src/frontend/web/react-site/src/generated/models/inline-response20076.ts
  src/frontend/web/react-site/src/generated/models/inline-response20077.ts
  src/frontend/web/react-site/src/generated/models/inline-response20079.ts
  src/frontend/web/react-site/src/generated/models/inline-response20080.ts
  src/frontend/web/react-site/src/generated/models/inline-response20081.ts
  src/frontend/web/react-site/src/generated/models/inline-response20083.ts
  src/frontend/web/react-site/src/generated/models/inline-response20084.ts
  src/frontend/web/react-site/src/generated/models/inline-response20085.ts
  src/frontend/web/react-site/src/generated/models/inline-response20088.ts
  src/frontend/web/react-site/src/generated/models/inline-response20089.ts
  src/frontend/web/react-site/src/generated/models/inline-response20090.ts
  src/frontend/web/react-site/src/generated/models/inline-response20091.ts
  src/frontend/web/react-site/src/generated/models/inline-response20093.ts
  src/frontend/web/react-site/src/generated/models/inline-response20097.ts
  src/frontend/web/react-site/src/generated/models/inline-response20098.ts
  src/frontend/web/react-site/src/generated/package.json
Labels: Feature

#338 Closes #337 - notification lors de la creation d'un parent
  src/backend/laravel-app/app/Http/Controllers/API/ParentsController.php
Labels: Feature

#342 Closes #341 - base structure for website and parent auth case handle
  src/backend/laravel-app/app/Http/Controllers/API/ConseilDisciplineController.php
  src/backend/laravel-app/app/Http/Controllers/API/ConvocationController.php
  src/backend/laravel-app/app/Http/Controllers/API/EleveController.php
  src/backend/laravel-app/app/Http/Controllers/API/FauteController.php
  src/backend/laravel-app/app/Http/Controllers/API/ParentsController.php
  src/backend/laravel-app/app/Http/Controllers/API/SanctionPrevuController.php
  src/frontend/web/react-admin/src/generated/apis/conseil-disciplines-api.ts
  src/frontend/web/react-admin/src/generated/apis/convocation-api.ts
  src/frontend/web/react-admin/src/generated/apis/eleves-api.ts
  src/frontend/web/react-admin/src/generated/apis/fautes-api.ts
  src/frontend/web/react-admin/src/generated/apis/parents-api.ts
  src/frontend/web/react-admin/src/generated/apis/sanctionprevus-api.ts
  src/frontend/web/react-site/src/App.css
  src/frontend/web/react-site/src/components/AppSwitch/AppSwitch.tsx
  src/frontend/web/react-site/src/components/MesEnfants/MesEnfants.tsx
  src/frontend/web/react-site/src/components/common/header/Header.tsx
  src/frontend/web/react-site/src/components/common/heading/Heading.tsx
  src/frontend/web/react-site/src/components/fautesanction/FauteSanction.jsx
  src/frontend/web/react-site/src/components/fautesanction/FauteSanction.tsx
  src/frontend/web/react-site/src/components/home/hero/Hero.css
  src/frontend/web/react-site/src/components/login/login.tsx
  src/frontend/web/react-site/src/components/pageEleve/PageEleve.tsx
  src/frontend/web/react-site/src/components/pageEleve/components/FautesSection.tsx
  src/frontend/web/react-site/src/components/team/TeamCard.tsx
  src/frontend/web/react-site/src/generated/apis/conseil-disciplines-api.ts
  src/frontend/web/react-site/src/generated/apis/convocation-api.ts
  src/frontend/web/react-site/src/generated/apis/fautes-api.ts
  src/frontend/web/react-site/src/generated/apis/parents-api.ts
  src/frontend/web/react-site/src/generated/apis/reglement-interieurs-api.ts
  src/frontend/web/react-site/src/generated/apis/regles-api.ts
  src/frontend/web/react-site/src/generated/apis/reparations-api.ts
  src/frontend/web/react-site/src/generated/apis/roles-api.ts
  src/frontend/web/react-site/src/generated/apis/sanctionprevus-api.ts
  src/frontend/web/react-site/src/generated/apis/suggestions-api.ts
  src/frontend/web/react-site/src/generated/apis/users-api.ts
  src/frontend/web/react-site/src/generated/models/inline-response20071.ts
  src/frontend/web/react-site/src/generated/models/inline-response20072.ts
  src/frontend/web/react-site/src/generated/models/inline-response20073.ts
  src/frontend/web/react-site/src/generated/models/inline-response20075.ts
  src/frontend/web/react-site/src/generated/models/inline-response20076.ts
  src/frontend/web/react-site/src/generated/models/inline-response20077.ts
  src/frontend/web/react-site/src/generated/models/inline-response20080.ts
  src/frontend/web/react-site/src/generated/models/inline-response20081.ts
  src/frontend/web/react-site/src/generated/models/inline-response20084.ts
  src/frontend/web/react-site/src/generated/models/inline-response20085.ts
  src/frontend/web/react-site/src/generated/models/inline-response20089.ts
  src/frontend/web/react-site/src/generated/models/inline-response20090.ts
  src/frontend/web/react-site/src/generated/models/inline-response20091.ts
  src/frontend/web/react-site/src/generated/models/inline-response20097.ts
  src/frontend/web/react-site/src/generated/models/inline-response20098.ts
Labels: Feature

#344 Closes #343 -integration des fautes et convocations des élèves
  .vscode/settings.json
  src/frontend/web/react-site/src/components/common/back/Backs.tsx
  src/frontend/web/react-site/src/components/common/footer/Footer.tsx
  src/frontend/web/react-site/src/components/common/header/DropdownUser.tsx
  src/frontend/web/react-site/src/components/common/header/header.css
  src/frontend/web/react-site/src/components/convocation/Convocation.tsx
  src/frontend/web/react-site/src/components/convocation/convocation.css
  src/frontend/web/react-site/src/components/fautesanction/FauteSanction.tsx
Labels: Feature

#348 Closes #347 - Modification des views parents ,eleves,enseignants,et p…
  .vscode/settings.json
  src/frontend/web/react-admin/src/pages/Eleve/components/DisplayEleves.css
  src/frontend/web/react-admin/src/pages/Eleve/components/DisplayEleves.tsx
  src/frontend/web/react-admin/src/pages/Eleve/components/DisplayOneModal.tsx
  src/frontend/web/react-admin/src/pages/Personnel/components/DisplayOneModal.tsx
  src/frontend/web/react-admin/src/pages/Personnel/components/DisplayPersonnels.css
  src/frontend/web/react-admin/src/pages/Personnel/components/DisplayPersonnels.tsx
  src/frontend/web/react-admin/src/pages/Professeur/components/DisplayOneModal.tsx
  src/frontend/web/react-admin/src/pages/Professeur/components/DisplayProfesseurs.css
  src/frontend/web/react-admin/src/pages/Professeur/components/DisplayProfesseurs.tsx
  src/frontend/web/react-site/src/generated/apis/sanctionprevus-api.ts
Labels: Feature

#350 Closes #349 - Adjustement
  src/backend/laravel-app/app/Http/Controllers/API/AuthController.php
  src/backend/laravel-app/app/Http/Controllers/API/ParentsController.php
  src/backend/laravel-app/composer.json
  src/backend/laravel-app/composer.lock
  src/backend/laravel-app/routes/api.php
  src/frontend/web/react-admin/src/components/DropdownMessage.tsx
  src/frontend/web/react-admin/src/components/DropdownNotification.tsx
  src/frontend/web/react-admin/src/components/Header.tsx
  src/frontend/web/react-admin/src/components/Sidebar.tsx
  src/frontend/web/react-admin/src/components/css/DisplaySuggestion.css
  src/frontend/web/react-admin/src/pages/Authentication/SignIn/SignIn.tsx
  src/frontend/web/react-admin/src/pages/Profile.tsx
  src/frontend/web/react-site/src/components/common/back/Back.tsx
  src/frontend/web/react-site/src/components/login/login.tsx
  src/frontend/web/react-site/src/components/pageEleve/PageEleve.tsx
  src/frontend/web/react-site/src/components/pageEleve/components/FautesSection.tsx
Labels: Feature

#352 Closes #351 - creation de l'endpoint pour l'affichage des eleves les …
  src/backend/laravel-app/app/Http/Controllers/API/EleveController.php
  src/backend/laravel-app/app/Http/Controllers/API/FauteController.php
  src/backend/laravel-app/routes/api.php
Labels: Feature

#357 Closes #356 - audio terminé et notifications bientot terminées
  .DS_Store
  src/.DS_Store
  src/frontend/.DS_Store
  src/frontend/mobile/flutter_app/android/app/build.gradle
  src/frontend/mobile/flutter_app/android/app/proguard-rules.pro
  src/frontend/mobile/flutter_app/android/app/src/main/AndroidManifest.xml
  src/frontend/mobile/flutter_app/ios/Podfile
  src/frontend/mobile/flutter_app/ios/Podfile.lock
  src/frontend/mobile/flutter_app/ios/Runner.xcodeproj/project.pbxproj
  src/frontend/mobile/flutter_app/ios/Runner.xcworkspace/contents.xcworkspacedata
  src/frontend/mobile/flutter_app/ios/Runner/AppDelegate.swift
  src/frontend/mobile/flutter_app/ios/Runner/Info.plist
  src/frontend/mobile/flutter_app/lib/common/configurations/api_configuration.dart
  src/frontend/mobile/flutter_app/lib/common/logics/speech/speech_cubit.dart
  src/frontend/mobile/flutter_app/lib/common/logics/speech/speech_cubit.freezed.dart
  src/frontend/mobile/flutter_app/lib/common/logics/speech/speech_state.dart
  src/frontend/mobile/flutter_app/lib/common/services/app_life_cycle.dart
  src/frontend/mobile/flutter_app/lib/common/services/notification_service.dart
  src/frontend/mobile/flutter_app/lib/common/services/pusher_service.dart
  src/frontend/mobile/flutter_app/lib/common/services/socket_io.dart
  src/frontend/mobile/flutter_app/lib/common/views/page_skeleton.dart
  src/frontend/mobile/flutter_app/lib/common/views/page_skeleton_two.dart
  src/frontend/mobile/flutter_app/lib/common/widgets/common_widgets.dart
  src/frontend/mobile/flutter_app/lib/common/widgets/fields.dart
  src/frontend/mobile/flutter_app/lib/features/authentication/logic/authentication/bloc/authentication_bloc.dart
  src/frontend/mobile/flutter_app/lib/features/authentication/views/login_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/logic/home_cubit.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/conseil_discipline_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/convocation_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/cours_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/fautes_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/home_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/reglements_interieurs_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/sanctions_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/views/student_statistics_page.dart
  src/frontend/mobile/flutter_app/lib/features/home/widgets/convocation_component.dart
  src/frontend/mobile/flutter_app/lib/features/home/widgets/home_component.dart
  src/frontend/mobile/flutter_app/lib/features/profile/logic/profile_cubit.dart
  src/frontend/mobile/flutter_app/lib/features/profile/logic/profile_cubit.freezed.dart
  src/frontend/mobile/flutter_app/lib/features/profile/logic/profile_state.dart
  src/frontend/mobile/flutter_app/lib/features/profile/views/parent_consultation_page.dart
  src/frontend/mobile/flutter_app/lib/features/profile/views/profile_page.dart
  src/frontend/mobile/flutter_app/lib/main.dart
  src/frontend/mobile/flutter_app/lib/repositories/auth_repository.dart
  src/frontend/mobile/flutter_app/pubspec.lock
  src/frontend/mobile/flutter_app/pubspec.yaml
  src/frontend/mobile/flutter_app/windows/flutter/generated_plugin_registrant.cc
  src/frontend/mobile/flutter_app/windows/flutter/generated_plugins.cmake
Labels: Feature

#360 Closes #353 - ajout ou envoie des notifications temps reel cote backend
  src/backend/laravel-app/app/Events/ConseilDisciplineCreatedEvent.php
  src/backend/laravel-app/app/Events/ConvocationCreatedEvent.php
  src/backend/laravel-app/app/Events/FauteCreatedEvent.php
  src/backend/laravel-app/app/Events/SanctionCreatedEvent.php
  src/backend/laravel-app/app/Http/Controllers/API/ConseilDisciplineController.php
  src/backend/laravel-app/app/Http/Controllers/API/ConvocationController.php
  src/backend/laravel-app/app/Http/Controllers/API/FauteController.php
  src/backend/laravel-app/app/Http/Controllers/API/ParentsController.php
  src/backend/laravel-app/app/Http/Controllers/API/SanctionPrevuController.php
  src/backend/laravel-app/composer.json
  src/backend/laravel-app/composer.lock
  src/backend/laravel-app/database/migrations/2023_05_30_000015_create_membre_conseils_table.php
  src/backend/laravel-app/database/migrations/2023_05_31_000016_create_sanction_prevus_table.php
  src/backend/laravel-app/database/migrations/2023_06_28_224602_create_avoir_membre_conseil_disciplines_table.php
Labels: Feature

#366 Closes #365 - Integration de l'API de suggestion cote website
  src/frontend/web/react-site/src/components/common/back/Back.tsx
  src/frontend/web/react-site/src/components/common/header/Head.tsx
  src/frontend/web/react-site/src/components/common/header/Header.tsx
  src/frontend/web/react-site/src/components/common/heading/Heading.tsx
  src/frontend/web/react-site/src/components/pageEleve/components/FautesSection.tsx
Labels: Feature

#368 Closes #367 - Website arranged
  src/backend/laravel-app/app/Http/Controllers/API/EleveController.php
  src/backend/laravel-app/app/Http/Controllers/API/ProfesseurController.php
  src/backend/laravel-app/routes/api.php
  src/frontend/web/react-admin/src/generated/apis/eleves-api.ts
  src/frontend/web/react-admin/src/generated/apis/parents-api.ts
  src/frontend/web/react-admin/src/generated/apis/professeurs-api.ts
  src/frontend/web/react-admin/src/generated/models/parents-create-body.ts
  src/frontend/web/react-admin/src/generated/models/update-parent-id-body.ts
  src/frontend/web/react-site/public/images/team/user.jpeg
  src/frontend/web/react-site/src/components/about/About.jsx
  src/frontend/web/react-site/src/components/about/about.css
  src/frontend/web/react-site/src/components/common/header/Head.tsx
  src/frontend/web/react-site/src/components/common/header/Header.tsx
  src/frontend/web/react-site/src/components/common/heading/Heading.tsx
  src/frontend/web/react-site/src/components/contact/Contact.jsx
  src/frontend/web/react-site/src/components/fautesanction/FauteSanction.tsx
  src/frontend/web/react-site/src/components/home/Home.jsx
  src/frontend/web/react-site/src/components/home/testimonal/Testimonal.jsx
  src/frontend/web/react-site/src/components/home/testimonal/Testimonal.tsx
  src/frontend/web/react-site/src/components/login/login.tsx
  src/frontend/web/react-site/src/components/pageEleve/components/FautesSection.tsx
  src/frontend/web/react-site/src/components/team/Team.jsx
  src/frontend/web/react-site/src/components/team/TeamCard.tsx
  src/frontend/web/react-site/src/generated/apis/eleves-api.ts
  src/frontend/web/react-site/src/generated/apis/parents-api.ts
  src/frontend/web/react-site/src/generated/apis/professeurs-api.ts
  src/frontend/web/react-site/src/generated/models/parents-create-body.ts
  src/frontend/web/react-site/src/generated/models/update-parent-id-body.ts
Labels: Feature

#370 Closes #369 - ajout de l'api contacter
  src/backend/laravel-app/app/Http/Controllers/API/OtherController.php
  src/backend/laravel-app/database/seeders/UserSeeder.php
  src/backend/laravel-app/routes/api.php
Labels: Feature

#372 Closes #371 - Integration des statistiques cote website
  src/frontend/web/react-admin/src/components/CardFour.tsx
  src/frontend/web/react-admin/src/components/CardThree.tsx
  src/frontend/web/react-admin/src/pages/Profile.tsx
  src/frontend/web/react-site/src/components/about/Awrapper.jsx
  src/frontend/web/react-site/src/components/about/Awrapper.tsx
  src/frontend/web/react-site/src/components/allcourses/OnlineCourses.jsx
  src/frontend/web/react-site/src/components/common/header/Header.tsx
  src/frontend/web/react-site/src/components/contact/Contact.jsx
  src/frontend/web/react-site/src/components/home/testimonal/Testimonal.tsx
  src/frontend/web/react-site/src/dummydata.js
Labels: Feature

#374 Closes #373 - ajout d'autres configurations backend
  src/backend/laravel-app/app/Http/Controllers/API/ParentsController.php
Labels: Feature

#379 Endpoints commit
  .gitignore
  src/frontend/web/react-admin/src/generated/apis/contact-api.ts
  src/frontend/web/react-admin/src/generated/models/api-contact-body.ts
  src/frontend/web/react-admin/src/generated/models/inline-response200100.ts
  src/frontend/web/react-admin/src/generated/models/inline-response200101.ts
  src/frontend/web/react-admin/src/generated/models/inline-response200102.ts
  src/frontend/web/react-admin/src/generated/models/inline-response200103.ts
  src/frontend/web/react-admin/src/generated/models/inline-response40040-error.ts
  src/frontend/web/react-admin/src/generated/models/inline-response40040.ts
  src/frontend/web/react-admin/src/generated/models/inline-response40450.ts
  src/frontend/web/react-admin/src/generated/models/validate-reparation-id-body.ts
  src/frontend/web/react-site/src/generated/apis/contact-api.ts
  src/frontend/web/react-site/src/generated/models/api-contact-body.ts
  src/frontend/web/react-site/src/generated/models/inline-response200100.ts
  src/frontend/web/react-site/src/generated/models/inline-response200101.ts
  src/frontend/web/react-site/src/generated/models/inline-response200102.ts
  src/frontend/web/react-site/src/generated/models/inline-response200103.ts
  src/frontend/web/react-site/src/generated/models/inline-response20096.ts
  src/frontend/web/react-site/src/generated/models/inline-response40039-error.ts
  src/frontend/web/react-site/src/generated/models/inline-response40039.ts
  src/frontend/web/react-site/src/generated/models/inline-response40040-error.ts
  src/frontend/web/react-site/src/generated/models/inline-response40040.ts
  src/frontend/web/react-site/src/generated/models/inline-response40450.ts
  src/frontend/web/react-site/src/generated/models/update-suggestion-id-body.ts
  src/frontend/web/react-site/src/generated/models/validate-reparation-id-body.ts
Labels: Fixe

#381 Test
  src/frontend/web/react-admin/src/pages/Dashboard/DashBoard.tsx
  src/frontend/web/react-site/src/components/about/Awrapper.tsx
  src/frontend/web/react-site/src/components/allcourses/CoursesCard.jsx
Labels: Feature

#382 Update AppSwitch.tsx
  src/frontend/web/react-admin/src/pages/AppSwitch/AppSwitch.tsx
Labels: Fixe

#383 Update FautesSection.tsx
  src/frontend/web/react-site/src/components/pageEleve/components/FautesSection.tsx
Labels: Fixe, Feature
